Azure/terraform-azurerm-avm-ptn-alz

main.tf
Resolves this issue described in #12
=> fix: Implement fix for Bug: Display Name property missing from policy assignments #12

README.md, _header.md, main.tf, variables.tf
This PR implements the proposed feature request in #10. There was also some minor cleanup to the README.md and header.md files to ensure the manual changes made in the generated README.md file are retained when updating the module.
=> feat: Implement support for policy_assignments_to_add and private_dns_zone_resource_group_id

.github/workflows/e2e.yml, examples/alzreference/terraform.tf, examples/dynamic-input/terraform.tf
This PR fixes timeout when using new e2e test process with OIDC auth.
=> Fix OIDC timeout on e2e tests

README.md, examples/alzreference/README.md, examples/alzreference/main.tf, examples/alzreference/terraform.tf, examples/default/README.md, examples/default/_header.md, examples/dynamic-input/README.md, examples/dynamic-input/locals.tf, examples/dynamic-input/main.tf, examples/dynamic-input/outputs.tf, examples/policy-assignment-modification-with-custom-lib/README.md, examples/policy-assignment-modification-with-custom-lib/_header.md, examples/policy-assignment-modification-with-custom-lib/lib/archetype_override_root.json, examples/policy-assignment-modification-with-custom-lib/lib/policy_assignment_updatering1.json, examples/policy-assignment-modification-with-custom-lib/main.tf, examples/policy-assignment-modification-with-custom-lib/terraform.tf, locals.telemetry.tf, locals.tf, locals.version.tf.json, main.telemetry.tf, main.tf, outputs.tf, terraform.tf, variables.telemetry.tf, variables.tf
Fixes some dependency issues by using a computed value as output, resulting in a much more sane dependency graph.
=> fix: dependency issues

.github/workflows/scorecard.yml, README.md, _header.md
Add OpenSFF Scorecard and badge
=> Add OpenSFF Scorecard

README.md, examples/policy-assignment-modification-with-custom-lib/README.md, examples/policy-assignment-modification-with-custom-lib/lib/log_analytics.alz_default_policy_value.yaml, examples/policy-assignment-modification-with-custom-lib/main.tf, examples/policy-assignment-modification-with-custom-lib/terraform.tf, main.tf, outputs.tf, terraform.tf, variables.telemetry.tf, variables.tf
=> feat: default policy values

README.md
=> docs: fix error in example

README.md, _header.md
=> docs: add gitignore notice

README.md, _header.md
=> docs: update exampel code

README.md, _header.md, avm.tflint.override.hcl, avm.tflint.override_module.hcl, avm.tflint_module.override.hcl, locals.tf, main.hierarchysettings.tf, main.telemetry.tf, tests/hierarchysettings.tftest.hcl, variables.tf
=> feat: add hierarchy settings

README.md, locals.tf, main.hierarchy_settings.tf, main.subscription_placement.tf, variables.tf
=> feat: subscription placement

README.md, _header.md
=> docs: spelling mistake in _header

.github/workflows/e2e.yml, README.md, avm, avm.bat, main.hierarchy_settings.tf, main.telemetry.tf, terraform.tf, tests/unit/existingmanagementgroup.tftest.hcl, tests/unit/hierarchysettings.tftest.hcl, tests/unit/testdata/existingmg/existingmg.alz_architecture_definition.yml, variables.tf
=> fix: exist mg issue + idempotency for hierarchy settings

README.md, main.role_definitions.tf, terraform.tf, tests/integration/modules/tenant_id/main.tf, tests/integration/multipleroledefs.tftest.hcl, tests/integration/testdata/multipleroledefs/test-role-definition.alz_role_definition.json, tests/integration/testdata/multipleroledefs/test.alz_archetype_definition.yml, tests/integration/testdata/multipleroledefs/test.alz_architecture_definition.yml, variables.tf
=> fix: role definition uniqueness

locals.tf
=> fix: allow module to work with deferral

README.md, _header.md, avm.tflint_example.override.hcl, examples/default/README.md, examples/default/terraform.tf, examples/management/README.md, examples/management/_header.md, examples/management/main.tf, examples/management/terraform.tf, examples/policy-assignment-modification-with-custom-lib/README.md, examples/policy-assignment-modification-with-custom-lib/main.tf, examples/policy-assignment-modification-with-custom-lib/terraform.tf, examples/template-architecture-definition/README.md, examples/template-architecture-definition/terraform.tf, terraform.tf, tests/integration/modules/tenant_id/main.tf, variables.tf
- Support for the release version of azapi 2.0
- Adds example for mgmt module
- fixes #132 
```
Apply complete! Resources: 388 added, 0 changed, 0 destroyed.
```
```
Apply complete! Resources: 421 added, 0 changed, 0 destroyed.
```
```
Apply complete! Resources: 250 added, 0 changed, 0 destroyed.
```
Verified all idempotent
Dependent on Azure/terraform-azurerm-avm-ptn-alz-management#74
=> feat: azapi 2.0.1

main.subscription_placement.tf
=> fix: subscription placement dependency on mg

README.md, _header.md, examples/management/README.md, examples/management/main.tf, examples/privatednszones/README.md, examples/privatednszones/_header.md, examples/privatednszones/main.tf, examples/privatednszones/terraform.tf, main.policy_assignments.tf, main.policy_role_assignments.tf, terraform.tf, variables.tf
Adds capability to add dependencies for policy assignments and policy role assignments.
This provides a nice workaround to the limitation of not being able to pass unknown values into the alz provider.
=> feat: add dependency management

README.md, _header.md
=> docs: remove duplicate paragraph

README.md, examples/default/README.md, examples/default/main.tf, examples/management/README.md, examples/management/main.tf, examples/management/variables.tf, examples/policy-assignment-modification-with-custom-lib/README.md, examples/policy-assignment-modification-with-custom-lib/main.tf, examples/privatednszones/README.md, examples/privatednszones/main.tf, examples/privatednszones/variables.tf, examples/role-assignments/README.md, examples/role-assignments/main.tf, locals.tf, main.hierarchy_settings.tf, main.management_groups.tf, main.policy_assignments.tf, main.policy_definitions.tf, main.policy_role_assignments.tf, main.policy_set_definitions.tf, main.role_assignments.tf, main.role_definitions.tf, main.subscription_placement.tf, main.telemetry.tf, variables.deprecated.tf, variables.role_assignments.tf, variables.telemetry.tf, variables.tf
Implements the pre-existing non compliance message behaviour from CAF module in a naieve, but functional way.
=> fix: policy non compliance messages
